import HomePage from "@/templates/HomePage";
import { NextPage } from "next";
import Head from "next/head";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>savelink</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <HomePage />
    </>
  );
};

export default Index;
